### ISSUE TITLE
HTTPS support in ONIE

### ISSUE THREAD

**Issue by lakesh-sharma** [opencomputeproject/onie#292] opened 2015-11-05 21:34 UTC
This is an enhancement request to add HTTPS support in onie infra.
ONIE self-update and nos-install infra uses busybox based wget, which does not support https.

HTTPS can be added by use wget package (instead of busybox based). I did try to add wget package,
it seems to require SSL type additional package, which could be gnutls or openssl.
I could not successfully build and integrate openssl and gnutls. So some one with more expertise can take a look in this feature.

**Comment by lakesh-sharma** [comment] 2015-11-05 21:39
Can we pls add help-wanted label to this issue.

**Comment by cbrune** [comment] 2015-11-05 22:03
Duplicate of #68

**Closed by cbrune** 2015-11-05 22:03 UTC
